<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions name='GetSRSInformationInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
                  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
                  xmlns:xs='http://www.w3.org/2001/XMLSchema'
                  xmlns:tjsr='urn:riv:clinicalprocess:healthcond:rehabilitation:GetSRSInformationResponder:1'
                  xmlns:tns='urn:riv:clinicalprocess:healthcond:rehabilitation:GetSRSInformation:1:rivtabp21'
                  targetNamespace='urn:riv:clinicalprocess:healthcond:rehabilitation:GetSRSInformation:1:rivtabp21'>
    <wsdl:types>
        <xs:schema targetNamespace='urn:riv:clinicalprocess:healthcond:rehabilitation:GetSRSInformation:1:rivtabp21'>
            <xs:import schemaLocation='GetSRSInformationResponder_1.0.xsd'
                       namespace='urn:riv:clinicalprocess:healthcond:rehabilitation:GetSRSInformationResponder:1'/>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name='GetSRSInformationRequest'>
        <wsdl:part name='parameters' element='tjsr:GetSRSInformationRequest'/>
    </wsdl:message>

    <wsdl:message name='GetSRSInformationResponse'>
        <wsdl:part name='parameters' element='tjsr:GetSRSInformationResponse'/>
    </wsdl:message>

    <wsdl:portType name='GetSRSInformationResponderInterface'>
        <wsdl:operation name='GetSRSInformation'>
            <wsdl:input message='tns:GetSRSInformationRequest'/>
            <wsdl:output message='tns:GetSRSInformationResponse'/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name='GetSRSInformationResponderBinding' type='tns:GetSRSInformationResponderInterface'>
        <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http'/>
        <wsdl:operation name='GetSRSInformation'>
            <soap:operation
                    soapAction='urn:riv:clinicalprocess:healthcond:rehabilitation:GetSRSInformationResponder:1:GetSRSInformation'
                    style='document'/>
            <wsdl:input>
                <soap:header use='literal' message='tns:GetSRSInformationRequest' part='LogicalAddress'/>
                <soap:body use='literal' parts='parameters'/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use='literal'/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name='GetSRSInformationResponderService'>
        <wsdl:port name='GetSRSInformationResponderPort' binding='tns:GetSRSInformationResponderBinding'>
            <soap:address location='http://tempuri.org'/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
