project.name=intyg

artifact.name=srs
artifact.version=2.0.0.9

git.url=https://github.com/sklintyg/srs.git
git.branch=main

builder.image=app-builder-image
builder.image.tag=21.0.2

runtime.image=srs-base-image
runtime.image.tag=21.0.9

build.args=build