---

- name: Delete application resources folder
  file:
    state: absent
    path: "{{ app_resources_folder }}"

- name: Create application resources folder
  file:
    state: directory
    path: "{{ app_resources_folder }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"

- name: Copy application resources
  copy:
    src: "{{ app_resources_src }}"
    dest: "{{ app_resources_folder }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"

- name: remove test resrouces models
  file:
      state: absent
      path: "{{ app_resources_folder }}/model"
  when: update_models|bool

- name: remove test resrouces images
  file:
      state: absent
      path: "{{ app_resources_folder }}/statistik"
  when: update_statistik|bool

- name: Copy application resources models
  copy:
    src: "{{ resources_models_folder }}"
    dest: "{{ app_resources_folder }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
  when: update_models|bool

- name: Copy application resources statistik
  copy:
    src: "{{ resources_statistik_folder }}"
    dest: "{{ app_resources_folder }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
  when: update_statistik|bool
