---

- name: Delete application resources folder
  file:
    state: absent
    path: "{{ app_resources_folder }}"
  when: reload_resources|bool

- name: Create application resources folder
  file:
    state: directory
    path: "{{ app_resources_folder }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
  when: reload_resources|bool

- name: Copy application resources
  copy:
    src: "{{ app_resources_src }}"
    dest: "{{ app_resources_folder }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
  when: reload_resources|bool
