---

- name: Configure shared jdbc datasource for srs
  lineinfile:
    dest: "{{ tomcat_conf }}/server.xml"
    regexp: "    <Resource name='sharedSrs'"
    insertbefore: "  </GlobalNamingResources>"
    line: "    <Resource name='sharedSrs' global='sharedSrs'  auth='Container' type='javax.sql.DataSource' username='{{ database_username }}' password='{{ database_password }}' driverClassName='{{ database_driver }}' url='{{ database_url }}' maxActive='{{ database_pool_maxActive }}' maxIdle='{{ database_pool_maxIdle }}' minIdle='{{ database_pool_minIdle }}' initialSize='{{ database_pool_initialSize }}' validationQuery='SELECT 1' validationQueryTimeout='3' testWhileIdle='true' timeBetweenEvictionRunsMillis='300000' minEvictableIdleTimeMillis='60000' defaultAutocommit='false' />"

- name: Configure jdbc resource
  lineinfile:
    dest: "{{ tomcat_conf }}/context.xml"
    regexp: "    <ResourceLink name='jdbc/srs'|    <Resource name='jdbc/srs'"
    insertbefore: "</Context>"
    line: "    <ResourceLink name='jdbc/srs' global='sharedSrs' type='javax.sql.DataSource'/>"
