---

- name: Ensure that application resources folder exists
  file:
    state: directory
    path: "{{ app_resources_folder }}"

- name: Copy application resources
  copy:
    src: "{{ app_resources_src }}"
    dest: "{{ app_resources_folder }}"

- name: Stop tomcat
  service:
    name: "{{ tomcat_service }}"
    state: stopped
    pattern: "{{ tomcat_service }}"

- name: Create release directory
  file:
    path: "{{ releases_folder }}"
    state: directory

- name: Ensure dependency for maven_artifact module is installed
  yum:
    name: python-lxml
    state: present

- name: Retrieve war file from nexus
  maven_artifact: 
    repository_url: https://build-inera.nordicmedtest.se/nexus/content/repositories/releases
    group_id: se.inera.intyg.srs
    artifact_id: srs
    extension: war
    dest: "{{ releases_folder }}/srs-{{ version }}.war"
  when: deploy_from_repo|bool

- name: Using local war-file pointed out by localWarPath, instead of online repo
  copy:
    src: "{{ playbook_dir }}/../build/libs/srs-{{ version }}.war"
    dest: "{{ releases_folder}}/srs-{{ version }}.war"
  when: not deploy_from_repo|bool

- name: Deploy war-file to tomcat instance, overwriting 
  copy:
    remote_src: True
    src: "{{ releases_folder }}/srs-{{ version }}.war"
    dest: "{{ webapps_folder }}/ROOT.war"

- name: Start tomcat
  service:
    name: "{{ tomcat_service }}"
    state: restarted
    pattern: "{{ tomcat_service }}"

