---

- name: Download rJava_{{ rjava_version }}.tar.gz
  get_url:
    url: "http://ftp.acc.umu.se/mirror/CRAN/src/contrib/rJava_{{ rjava_version }}.tar.gz"
    dest: "{{ archive_dir }}/rJava_{{ rjava_version }}.tar.gz"

- name: Download pch_{{ pch_version }}.tar.gz
  get_url:
    url: "http://ftp.acc.umu.se/mirror/CRAN/src/contrib/pch_{{ pch_version }}.tar.gz"
    dest: "{{ archive_dir }}/pch_{{ pch_version }}.tar.gz"

# The installation directory does not change when the rJava version is changed, so to upgrade rJava,
# /usr/lib64/R/library/rJava/ must be manually removed.
- name: Install rJava into R runtime
  command: R CMD INSTALL "{{ archive_dir }}/rJava_{{ rjava_version }}.tar.gz"
  args:
    creates: /usr/lib64/R/library/rJava/DESCRIPTION

# Same problem as above.
- name: Install pch into R runtime
  command: R CMD INSTALL "{{ archive_dir }}/pch_{{ pch_version }}.tar.gz"
  args:
    creates: /usr/lib64/R/library/pch/DESCRIPTION

- name: Copy rdata files
  copy:
    src: "{{ playbook_dir }}/../models/"
    dest: "/opt/models"
